### ISSUE TITLE
Should This Repository Be Archived?

### ISSUE THREAD

**Issue by danforbes** [substrate-developer-hub/hacktoberfest#69]

**Comment by jimmychu0807** [comment]
@gnunicorn  we want to only keep projects we actively maintain under substrate-developer-hub and archive the rest. We are discussing if we should archive this project. What do you think of this? If you want, we can also transfer the ownership back to you. 

Otherwise, I am fine to archive this project.

**Comment by wheresaddie** [comment]
I think it makes sense to archive unless @gnunicorn wants to maintain it directly. TBD

**Comment by jimmychu0807** [comment]
I think we can just archiving this. Because if needed, we can always unarchive it back.
